### ISSUE TITLE
微博超话客户端签到接口的获取

### ISSUE THREAD

**Issue by ReaJason** [1343890272/weibo_comments#1]
请问，微博超话客户端签到接口是怎么获取的到的，想学习一下，我抓微博超话客户端获取的post的请求，而代码中是get请求，并且很好使

**Comment by wxy1343** [comment]
我是通过抓包+动态调试获取的，参考：https://www.52pojie.cn/forum.php?mod=viewthread&tid=658865  
get、post都行，data不带数据

**Comment by ReaJason** [comment]
谢谢，学习了
