### ISSUE TITLE
输入gsid后报错

### ISSUE THREAD

**Issue by Choicc** [1343890272/weibo_comments#2]
错误如下:
Traceback (most recent call last):
  File "main.py", line 1502, in <module>
    zero_handle(True)
  File "main.py", line 1231, in zero_handle
    for info in get_weibo_info(gsid):
  File "main.py", line 445, in get_weibo_info
    title = r.json()['data']['statuses'][i]['raw_text'][:-2]
KeyError: 'raw_text'

**Comment by wxy1343** [comment]
应该是你gsid不正确

**Comment by Choicc** [comment]
> 应该是你gsid不正确

我测试了一下，返回账号数据没错，但没有raw_text字段

**Comment by wxy1343** [comment]
改成这样试试
```
try:
    title = r.json()['data']['statuses'][i]['raw_text'][:-2]
except:
    title = r.json()['data']['statuses'][i]['text']
```
