### ISSUE TITLE
关于 cookie 获取

### ISSUE THREAD

**Issue by 951409031** [1343890272/weibo_comments#4]
测试得到 cookie 有效期, 大概只有四个小时, 有办法将获取 cookie 这里自动化掉吗
本来想要通过 selenium 做, 但是看到现在微博所有登录都要扫码了, 不知道可以解决吗

**Comment by wxy1343** [comment]
我一直都没过期啊，可能是一直有请求就不会过期吧

**Comment by wxy1343** [comment]
可以参考这个[仓库](https://github.com/UchihaMekura/AutoLogin_weibo)，通过私信方法验证
